# Site settings

#google_analytics: UA-NNNNNNNN-N

title: Where is James Ray ?
author: Rémi Debord
email: remidebord@hotmail.fr

url: https://jamesraymusic.github.io
description: Unofficial website of the American singer James Ray, known for the songs "If You Gotta Make a Fool of Somebody", "Itty Bitty Pieces", and "I've Got My Mind Set On you" covered by George Harrison in 1987.

header_pages:
  - index.md
  - biography.md
  - songs.md
  - photos.md
  - references.md
  - about.md

footer: 'follow us on <a href="https://youtube.com/@remidebord9237?si=uOFLTH6eOAEXN1DA">youtube</a> and <a href="https://twitter.com/">twitter</a>'

style: light
listen_for_clients_preferred_style: true # true or false (default)

# Comments
disqus:
  shortname: https-remidebord-github-io-whereisjamesray

plugins:
  - jekyll-seo-tag
